runtime: python39

env_variables:
  INSTANCE_CONNECTION_NAME: clothes-shop-428417:us-central1:clothes-shop
  DB_USER: postgres
  DB_PASS: Moein1378!@
  DB_NAME: postgres
  DB_HOST: 34.121.105.165
  DB_PORT: 5432

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT app:app

# optional, but recommended to avoid long timeouts
instance_class: F2

# optional, but recommended for Flask applications with sessions
# increasing max idle instances to improve startup time
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
